version: "3.7"
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=${ATHENA_DB_PASSWORD}
      - POSTGRES_USER=${ATHENA_DB_USERNAME}
      - POSTGRES_DB=${ATHENA_DB_NAME}
    image: postgres:12.1
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
